# Form implementation generated from reading ui file 'admin_menu.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.eventsTable = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.eventsTable.setColumnCount(8)
        self.eventsTable.setObjectName("eventsTable")
        self.eventsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.eventsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.eventsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.eventsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.eventsTable.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.eventsTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.eventRegistrationButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.eventRegistrationButton.setMinimumSize(QtCore.QSize(100, 30))
        self.eventRegistrationButton.setObjectName("eventRegistrationButton")
        self.horizontalLayout.addWidget(self.eventRegistrationButton)
        self.returnToAdminPreferencesButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.returnToAdminPreferencesButton.setObjectName("returnToAdminPreferencesButton")
        self.horizontalLayout.addWidget(self.returnToAdminPreferencesButton)
        self.mailButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.mailButton.setMinimumSize(QtCore.QSize(100, 30))
        self.mailButton.setObjectName("mailButton")
        self.horizontalLayout.addWidget(self.mailButton)
        self.exitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exitButton.setMinimumSize(QtCore.QSize(100, 30))
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout.addWidget(self.exitButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "EVENT ADMINISTRATION PANEL"))
        item = self.eventsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Meeting Date"))
        item = self.eventsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.eventsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", " Participan Email"))
        item = self.eventsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Organizer Email"))
        self.eventRegistrationButton.setText(_translate("MainWindow", "Event Registration"))
        self.returnToAdminPreferencesButton.setText(_translate("MainWindow", "Preferences"))
        self.mailButton.setText(_translate("MainWindow", "Mail"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
