# Form implementation generated from reading ui file 'applications.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ApplicationsPage(object):
    def setupUi(self, ApplicationsPage):
        ApplicationsPage.setObjectName("ApplicationsPage")
        ApplicationsPage.resize(700, 400)
        self.gridLayout_2 = QtWidgets.QGridLayout(ApplicationsPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.allAplicationsButton = QtWidgets.QPushButton(parent=ApplicationsPage)
        self.allAplicationsButton.setObjectName("allAplicationsButton")
        self.gridLayout.addWidget(self.allAplicationsButton, 0, 0, 1, 1)
        self.comboBox_filters = QtWidgets.QComboBox(parent=ApplicationsPage)
        self.comboBox_filters.setObjectName("comboBox_filters")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.comboBox_filters.addItem("")
        self.gridLayout.addWidget(self.comboBox_filters, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ReturnButton = QtWidgets.QPushButton(parent=ApplicationsPage)
        self.ReturnButton.setAutoRepeatInterval(100)
        self.ReturnButton.setObjectName("ReturnButton")
        self.horizontalLayout.addWidget(self.ReturnButton)
        self.closeButton = QtWidgets.QPushButton(parent=ApplicationsPage)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.searchInput = QtWidgets.QLineEdit(parent=ApplicationsPage)
        self.searchInput.setObjectName("searchInput")
        self.horizontalLayout_3.addWidget(self.searchInput)
        self.searchButton = QtWidgets.QPushButton(parent=ApplicationsPage)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout_3.addWidget(self.searchButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 2)
        self.ApplicationsTable = QtWidgets.QTableWidget(parent=ApplicationsPage)
        self.ApplicationsTable.setColumnCount(7)
        self.ApplicationsTable.setObjectName("ApplicationsTable")
        self.ApplicationsTable.setRowCount(0)
        self.gridLayout_2.addWidget(self.ApplicationsTable, 2, 0, 1, 2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.mentorDefinedButton = QtWidgets.QPushButton(parent=ApplicationsPage)
        self.mentorDefinedButton.setObjectName("mentorDefinedButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.mentorDefinedButton)
        self.mentorUndefinedButton = QtWidgets.QPushButton(parent=ApplicationsPage)
        self.mentorUndefinedButton.setObjectName("mentorUndefinedButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.mentorUndefinedButton)
        self.gridLayout_2.addLayout(self.formLayout, 1, 1, 1, 1)

        self.retranslateUi(ApplicationsPage)
        QtCore.QMetaObject.connectSlotsByName(ApplicationsPage)

    def retranslateUi(self, ApplicationsPage):
        _translate = QtCore.QCoreApplication.translate
        ApplicationsPage.setWindowTitle(_translate("ApplicationsPage", "Form"))
        self.allAplicationsButton.setText(_translate("ApplicationsPage", "All Applications"))
        self.comboBox_filters.setItemText(0, _translate("ApplicationsPage", "--- Select Filter ---"))
        self.comboBox_filters.setItemText(1, _translate("ApplicationsPage", "Duplicate Records"))
        self.comboBox_filters.setItemText(2, _translate("ApplicationsPage", "Previous VIT Check"))
        self.comboBox_filters.setItemText(3, _translate("ApplicationsPage", "Unique VIT Records"))
        self.comboBox_filters.setItemText(4, _translate("ApplicationsPage", "Filtered Applications"))
        self.ReturnButton.setText(_translate("ApplicationsPage", "Return to Preferences"))
        self.closeButton.setText(_translate("ApplicationsPage", "close"))
        self.searchInput.setPlaceholderText(_translate("ApplicationsPage", "search by name..."))
        self.searchButton.setText(_translate("ApplicationsPage", "search"))
        self.mentorDefinedButton.setText(_translate("ApplicationsPage", "Mentor Meeting Defined"))
        self.mentorUndefinedButton.setText(_translate("ApplicationsPage", "Mentor Interview Undefined"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ApplicationsPage = QtWidgets.QWidget()
    ui = Ui_ApplicationsPage()
    ui.setupUi(ApplicationsPage)
    ApplicationsPage.show()
    sys.exit(app.exec())
