# Form implementation generated from reading ui file 'applications.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys
import pandas as pd


class Ui_ApplicationsPage(object):
    def setupUi(self, ApplicationsPage):
        ApplicationsPage.setObjectName("ApplicationsPage")
        ApplicationsPage.resize(700, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(ApplicationsPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.searchInput = QtWidgets.QLineEdit(parent=ApplicationsPage)
        self.searchInput.setObjectName("searchInput")
        self.horizontalLayout_3.addWidget(self.searchInput)
        self.searchButton = QtWidgets.QPushButton(parent=ApplicationsPage)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout_3.addWidget(self.searchButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.allApplicationsButton = QtWidgets.QPushButton(parent=ApplicationsPage)
        self.allApplicationsButton.setObjectName("allApplicationsButton")
        self.horizontalLayout_2.addWidget(self.allApplicationsButton)
        self.mentorDefinedButton = QtWidgets.QPushButton(parent=ApplicationsPage)
        self.mentorDefinedButton.setObjectName("mentorDefinedButton")
        self.horizontalLayout_2.addWidget(self.mentorDefinedButton)
        self.mentorUndefinedButton = QtWidgets.QPushButton(parent=ApplicationsPage)
        self.mentorUndefinedButton.setObjectName("mentorUndefinedButton")
        self.horizontalLayout_2.addWidget(self.mentorUndefinedButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.ApplicationsTable = QtWidgets.QTableWidget(parent=ApplicationsPage)
        self.ApplicationsTable.setColumnCount(7)
        self.ApplicationsTable.setObjectName("ApplicationsTable")
        self.ApplicationsTable.setRowCount(0)
        self.verticalLayout.addWidget(self.ApplicationsTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.VIT1Button = QtWidgets.QPushButton(parent=ApplicationsPage)
        self.VIT1Button.setObjectName("VIT1Button")
        self.horizontalLayout.addWidget(self.VIT1Button)
        self.VIT2Button = QtWidgets.QPushButton(parent=ApplicationsPage)
        self.VIT2Button.setObjectName("VIT2Button")
        self.horizontalLayout.addWidget(self.VIT2Button)
        self.ReturnButton = QtWidgets.QPushButton(parent=ApplicationsPage)
        self.ReturnButton.setAutoRepeatInterval(100)
        self.ReturnButton.setObjectName("ReturnButton")
        self.horizontalLayout.addWidget(self.ReturnButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.retranslateUi(ApplicationsPage)
        QtCore.QMetaObject.connectSlotsByName(ApplicationsPage)

      
        
    def retranslateUi(self, ApplicationsPage):
        _translate = QtCore.QCoreApplication.translate
        ApplicationsPage.setWindowTitle(_translate("ApplicationsPage", "Form"))
        self.searchInput.setPlaceholderText(_translate("ApplicationsPage", "search..."))
        self.searchButton.setText(_translate("ApplicationsPage", "search"))
        self.allApplicationsButton.setText(_translate("ApplicationsPage", "All Applications"))
        self.mentorDefinedButton.setText(_translate("ApplicationsPage", "Mentor Meeting Defined"))
        self.mentorUndefinedButton.setText(_translate("ApplicationsPage", "Mentor Interview Undefined"))
        self.VIT1Button.setText(_translate("ApplicationsPage", "VIT1 Records"))
        self.VIT2Button.setText(_translate("ApplicationsPage", "VIT2 Records"))
        self.ReturnButton.setText(_translate("ApplicationsPage", "Return to Preferences"))

def load_data():
    """Drive/Yerel dosyadan veriyi çeker"""
    try:
        # Dosya adını ve yolunu kendi dosyanla değiştir (Örn: 'basvurular.xlsx')
        df = pd.read_excel("Basvurular.xlsx") 
        return df
    except Exception as e:
        print(f"Hata: Dosya okunamadi: {e}")
        return pd.DataFrame()

def display_on_table(df):
    """Pandas DataFrame'i ApplicationsTable isimli tabloya basar"""
    ui.ApplicationsTable.setRowCount(0)
    if df.empty:
        return

    ui.ApplicationsTable.setRowCount(len(df))
    ui.ApplicationsTable.setColumnCount(len(df.columns))

# Sütun başlıklarını ayarla
    ui.ApplicationsTable.setHorizontalHeaderLabels(df.columns.astype(str))

    for row_index, row_data in enumerate(df.values):
        for col_index, value in enumerate(row_data):
            ui.ApplicationsTable.setItem(row_index, col_index, QtWidgets.QTableWidgetItem(str(value)))

def handle_search():
    print("Arama butonuna basıldı!")
    """1. Ara Butonu: İsim Soyisim içinde arama yapar"""
    search_text = ui.searchInput.text().strip().lower()
    df = load_data()

    if not search_text or df.empty:
        return

# Sütun adın 'Ad Soyad' değilse burayı güncelle!
    filtered_df = df[df['Adınız Soyadınız'].str.contains(search_text, case=False, na=False)]
    display_on_table(filtered_df)

def handle_all_applications():
    """2. Tüm Başvurular Butonu: Tüm listeyi getirir"""
    df = load_data()
    display_on_table(df)

def handle_mentor_defined():
    """3- Mentor Gorusmesi Tanimlananlar"""
    df = load_data()
    if df.empty:
        return
    target_col = 'Mentor gorusmesi'
    if target_col in df.columns:
        filtered_df = df[df[target_col].astype(str).str.upper() == "OK"]        
        display_on_table(filtered_df)
    else:
        print(f"Hata: '{target_col}' sütunu bulunamadı.")

def handle_mentor_undefined():
    """4- Mentor Gorusmesi Tanimlanmayanlar"""
    df = load_data()
    if df.empty:
        return
    target_col = 'Mentor gorusmesi'
    if target_col in df.columns:
    # Mentor sütunu boş (NaN) olan veya boş metin içeren kayıtları getirir.
        filtered_df = df[(df[target_col].astype(str).str.upper() == "ATANMADI") | (df[target_col].isna())]        
        display_on_table(filtered_df)
    else:
        print(f"Hata: '{target_col}' sütunu bulunamadı.")

   

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ApplicationsPage = QtWidgets.QWidget()
    ui = Ui_ApplicationsPage()
    ui.setupUi(ApplicationsPage)
    ui.retranslateUi(ApplicationsPage)
    ui.searchButton.clicked.connect(handle_search)
    ui.allApplicationsButton.clicked.connect(handle_all_applications)
    # Mentor butonlarını bağlama
    ui.mentorDefinedButton.clicked.connect(handle_mentor_defined)
    ui.mentorUndefinedButton.clicked.connect(handle_mentor_undefined)
    ApplicationsPage.show()
    sys.exit(app.exec())
