# Form implementation generated from reading ui file 'interview.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btntxtsearch = QtWidgets.QLineEdit(parent=Form)
        self.btntxtsearch.setObjectName("btntxtsearch")
        self.horizontalLayout_2.addWidget(self.btntxtsearch)
        self.btnsearch_2 = QtWidgets.QPushButton(parent=Form)
        self.btnsearch_2.setObjectName("btnsearch_2")
        self.horizontalLayout_2.addWidget(self.btnsearch_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.btnProjectSubmitted = QtWidgets.QPushButton(parent=Form)
        self.btnProjectSubmitted.setObjectName("btnProjectSubmitted")
        self.verticalLayout.addWidget(self.btnProjectSubmitted)
        self.tableWidget = QtWidgets.QTableWidget(parent=Form)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnReturntoPreference = QtWidgets.QPushButton(parent=Form)
        self.btnReturntoPreference.setObjectName("btnReturntoPreference")
        self.horizontalLayout.addWidget(self.btnReturntoPreference)
        self.btnclose = QtWidgets.QPushButton(parent=Form)
        self.btnclose.setObjectName("btnclose")
        self.horizontalLayout.addWidget(self.btnclose)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btntxtsearch.setText(_translate("Form", "search..."))
        self.btnsearch_2.setText(_translate("Form", "search"))
        self.btnProjectSubmitted.setText(_translate("Form", "Project Submitted"))
        self.btnReturntoPreference.setText(_translate("Form", "Return to Preferences"))
        self.btnclose.setText(_translate("Form", "close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
