# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_loginpage(object):
    def setupUi(self, loginpage):
        loginpage.setObjectName("loginpage")
        loginpage.resize(550, 563)
        loginpage.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.centralwidget = QtWidgets.QWidget(parent=loginpage)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(370, 340, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(110, 30, 300, 400))
        self.widget.setMinimumSize(QtCore.QSize(300, 400))
        self.widget.setStyleSheet("/* Ana arka plan rengi */\n"
"QWidget {\n"
"    background-color: rgb(223, 223, 223);\n"
"    color: black; /* Tüm yazıların siyah olmasını zorla */\n"
"}\n"
"\n"
"/* Giriş kutularını beyaz yap ve yazıları belirginleştir */\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"/* Butonları daha belirgin yap */\n"
"QPushButton {\n"
"    background-color: #f0f0f0;\n"
"    color: black;\n"
"    border: 1px solid #777;\n"
"    padding: 5px;\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.userNameInput = QtWidgets.QLineEdit(parent=self.widget)
        self.userNameInput.setText("")
        self.userNameInput.setObjectName("userNameInput")
        self.verticalLayout.addWidget(self.userNameInput)
        self.passwordInput = QtWidgets.QLineEdit(parent=self.widget)
        self.passwordInput.setText("")
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.verticalLayout.addWidget(self.passwordInput)
        self.frame = QtWidgets.QFrame(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(320, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        self.loginButton = QtWidgets.QPushButton(parent=self.widget)
        self.loginButton.setObjectName("loginButton")
        self.verticalLayout.addWidget(self.loginButton)
        self.exitButton = QtWidgets.QPushButton(parent=self.widget)
        self.exitButton.setObjectName("exitButton")
        self.verticalLayout.addWidget(self.exitButton)
        self.hataLabel = QtWidgets.QLabel(parent=self.widget)
        self.hataLabel.setObjectName("hataLabel")
        self.verticalLayout.addWidget(self.hataLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        loginpage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=loginpage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 24))
        self.menubar.setObjectName("menubar")
        loginpage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=loginpage)
        self.statusbar.setObjectName("statusbar")
        loginpage.setStatusBar(self.statusbar)

        self.retranslateUi(loginpage)
        QtCore.QMetaObject.connectSlotsByName(loginpage)

    def retranslateUi(self, loginpage):
        _translate = QtCore.QCoreApplication.translate
        loginpage.setWindowTitle(_translate("loginpage", "MainWindow"))
        self.userNameInput.setPlaceholderText(_translate("loginpage", "Username"))
        self.passwordInput.setPlaceholderText(_translate("loginpage", "Password"))
        self.loginButton.setText(_translate("loginpage", "Login"))
        self.exitButton.setText(_translate("loginpage", "Exit"))
        self.hataLabel.setText(_translate("loginpage", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loginpage = QtWidgets.QMainWindow()
    ui = Ui_loginpage()
    ui.setupUi(loginpage)
    loginpage.show()
    sys.exit(app.exec())
