# Form implementation generated from reading ui file 'mentor_interview.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(621, 549)
        Dialog.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.layoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(35, 20, 511, 491))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchInput = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.searchInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.searchInput.setObjectName("searchInput")
        self.horizontalLayout.addWidget(self.searchInput)
        self.searchButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout.addWidget(self.searchButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.comboBox = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.mentorInterviewTable = QtWidgets.QTableWidget(parent=self.layoutWidget)
        self.mentorInterviewTable.setStyleSheet("background-color: rgb(201, 223, 255);")
        self.mentorInterviewTable.setRowCount(10)
        self.mentorInterviewTable.setColumnCount(4)
        self.mentorInterviewTable.setObjectName("mentorInterviewTable")
        item = QtWidgets.QTableWidgetItem()
        self.mentorInterviewTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.mentorInterviewTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.mentorInterviewTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.mentorInterviewTable.setHorizontalHeaderItem(3, item)
        self.verticalLayout_2.addWidget(self.mentorInterviewTable)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.returnButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.returnButton.setObjectName("returnButton")
        self.verticalLayout_3.addWidget(self.returnButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.searchInput.setText(_translate("Dialog", "Type to search..."))
        self.searchButton.setText(_translate("Dialog", "search"))
        self.pushButton_2.setText(_translate("Dialog", "All Conversations"))
        self.comboBox.setCurrentText(_translate("Dialog", "Select Filter"))
        self.comboBox.setItemText(0, _translate("Dialog", "Select Filter"))
        self.comboBox.setItemText(1, _translate("Dialog", "Mentor Name"))
        self.comboBox.setItemText(2, _translate("Dialog", "Date"))
        self.comboBox.setItemText(3, _translate("Dialog", "Topic"))
        self.comboBox.setItemText(4, _translate("Dialog", "Status"))
        item = self.mentorInterviewTable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Mentor Name"))
        item = self.mentorInterviewTable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Date"))
        item = self.mentorInterviewTable.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "New Column"))
        item = self.mentorInterviewTable.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Status"))
        self.returnButton.setText(_translate("Dialog", "Return to Preferences Screen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
