# Form implementation generated from reading ui file 'prefence_menu.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

#import gspread
#from oauth2client.service_account import ServiceAccountCredentials
from PyQt6 import QtCore, QtGui, QtWidgets
from applications import Ui_ApplicationsPage
from mentor_interview import Ui_Dialog # Dosya ve Class adını eşleştirdik
from interview import Ui_Form
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(618, 600)
        MainWindow.setMinimumSize(QtCore.QSize(618, 600))
        MainWindow.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(120, 80, 351, 331))
        self.widget.setStyleSheet("background-color: rgb(229, 229, 229);")
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 4, 1, 1)
        self.applicationsButton = QtWidgets.QPushButton(parent=self.widget)
        self.applicationsButton.setMinimumSize(QtCore.QSize(80, 50))
        self.applicationsButton.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.applicationsButton.setObjectName("applicationsButton")
        self.gridLayout.addWidget(self.applicationsButton, 1, 1, 1, 1)
        self.mentorMeetingButton = QtWidgets.QPushButton(parent=self.widget)
        self.mentorMeetingButton.setMinimumSize(QtCore.QSize(80, 50))
        self.mentorMeetingButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.mentorMeetingButton.setObjectName("mentorMeetingButton")
        self.gridLayout.addWidget(self.mentorMeetingButton, 1, 3, 1, 1)
        self.interviewButton = QtWidgets.QPushButton(parent=self.widget)
        self.interviewButton.setMinimumSize(QtCore.QSize(80, 50))
        self.interviewButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.interviewButton.setObjectName("interviewButton")
        self.gridLayout.addWidget(self.interviewButton, 4, 1, 1, 1)
        self.closeButton = QtWidgets.QPushButton(parent=self.widget)
        self.closeButton.setMinimumSize(QtCore.QSize(60, 50))
        self.closeButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.closeButton.setObjectName("closeButton")
        self.gridLayout.addWidget(self.closeButton, 4, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 5, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem3, 4, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem4, 3, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem5, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 618, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "preference_menu"))
        self.applicationsButton.setText(_translate("MainWindow", "Applications"))
        self.applicationsButton.setStyleSheet("background-color: white; color: black; font-weight: bold;")
        self.mentorMeetingButton.setText(_translate("MainWindow", "Mentor Meeting"))
        self.mentorMeetingButton.setStyleSheet("background-color: white; color: black; font-weight: bold;")
        self.interviewButton.setText(_translate("MainWindow", "Interviews"))
        self.interviewButton.setStyleSheet("background-color: white; color: black; font-weight: bold;")
        self.closeButton.setText(_translate("MainWindow", "Close"))
        self.closeButton.setStyleSheet("background-color: white; color: black; font-weight: bold;")
    
def open_applications():
# Pencerenin anında kapanmaması için global referans kullanıyoruz
    
    global apps_window
    # try:
    #     print("Applications button triggered!") # Terminalde bunu görmeliyiz
    apps_window = QtWidgets.QWidget()
    ui_apps = Ui_ApplicationsPage()
    ui_apps.setupUi(apps_window)
    ui_apps.retranslateUi(apps_window)
    apps_window.show()
    #     print("sayfa basariyla acildi.")
    # except Exception as e:
    #     print(f"sayfa acilirken hata olustu: {e}")   
    # 
def open_mentor_interview():
    global mentor_dialog
    mentor_dialog = QtWidgets.QWidget()
    ui_mentor = Ui_Dialog()
    ui_mentor.setupUi(mentor_dialog)
    ui_mentor.retranslateUi(mentor_dialog)

    mentor_dialog.setStyleSheet("""
            QWidget { 
                color: black; 
            }
            QPushButton { 
                background-color: rgb(225, 225, 225); 
                color: black; 
            }
            QLineEdit {
                color: black;
                background-color: white;
            }
            QTableWidget {
                color: black;
                gridline-color: gray;
            }
        """)
        # ------------------------------------------
        
        # Return butonuna basınca kapanması için:
    ui_mentor.returnButton.clicked.connect(mentor_dialog.close)
    
    mentor_dialog.show() 

def open_interview():
    global interview_window
    try:
        from interview import Ui_Form
        interview_window = QtWidgets.QWidget()
        ui_inter = Ui_Form()
        ui_inter.setupUi(interview_window)
        ui_inter.retranslateUi(interview_window)
        
        # Renklerin siyah görünmesi için (daha önce yaşadığımız sorun için önlem)
        #interview_window.setStyleSheet("QWidget { color: black; }")
        
        # 'Return' butonunu çalıştıralım
        ui_inter.btnReturntoPreference.clicked.connect(interview_window.close)
        
        # 'Close' butonunu çalıştıralım
        ui_inter.btnclose.clicked.connect(interview_window.close)

        interview_window.show()
        print("Interviews sayfası başarıyla açıldı.")
    except Exception as e:
        print(f"Hata: {e}")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)

    print("Sistem baslatiliyor...") # 1. Bunu gormeliyiz

    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.retranslateUi(MainWindow)
   
  
    ui.applicationsButton.clicked.connect(open_applications)
    ui.mentorMeetingButton.clicked.connect(open_mentor_interview)
    ui.interviewButton.clicked.connect(open_interview)
    # Close butonuna basınca ana pencereyi kapatır
    ui.closeButton.clicked.connect(MainWindow.close)
    print("Arayuz yuklendi, butonlar baglaniyor...")

    MainWindow.show()
    sys.exit(app.exec())
